apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        actorSystemName: {{ .Values.name }}
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: application-conf
          configMap:
            name: airbyte.application.conf
            defaultMode: 420
        - name: logback-conf
          configMap:
            name: airbyte.logback.xml
            defaultMode: 420
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.imageName }}:{{ .Values.version }}
          command: ["bin/datamesh-airbytespecificprovisioner"]
          args: ["-Dconfig.file=etc/app-conf/airbyte.application.conf", "-Dlogback.configurationFile=etc/log-conf/airbyte.logback.xml", "-Dconfig.override_with_env_vars=true"]
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          #          Removing readiness and liveliness because there's no such endpoint right now.
          #          To be fixed, totally a bad practice, but this is a mock.
          #          readinessProbe:
          #            httpGet:
          #              path: /ready
          #              port: management
          #            periodSeconds: 10
          #            failureThreshold: 5
          #            initialDelaySeconds: 30
          #          livenessProbe:
          #            httpGet:
          #              path: "/alive"
          #              port: management
          #            periodSeconds: 10
          #            failureThreshold: 5
          #            initialDelaySeconds: 30
          ports:
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8093
              protocol: TCP
          securityContext:
            runAsUser: 1001
            allowPrivilegeEscalation: false
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SNOWFLAKE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: SNOWFLAKE_HOST
            - name: SNOWFLAKE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: SNOWFLAKE_USER
            - name: SNOWFLAKE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: SNOWFLAKE_PASSWORD
            - name: SNOWFLAKE_ROLE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: SNOWFLAKE_ROLE
            - name: SNOWFLAKE_WAREHOUSE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: SNOWFLAKE_WAREHOUSE
            - name: AIRBYTE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: AIRBYTE_BASE_URL
            - name: AIRBYTE_WORKSPACE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: AIRBYTE_WORKSPACE_ID
            - name: AIRBYTE_SOURCE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: AIRBYTE_SOURCE_ID
            - name: AIRBYTE_DESTINATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: AIRBYTE_DESTINATION_ID
            - name: DBT_GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: DBT_GIT_TOKEN
            - name: DBT_GIT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: DBT_GIT_USER
            - name: AIRBYTE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: AIRBYTE_USERNAME
            - name: AIRBYTE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: AIRBYTE_PASSWORD
            - name: AIRBYTE_BASIC_AUTH_ENABLED
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: AIRBYTE_BASIC_AUTH_ENABLED
          volumeMounts:
            - name: application-conf
              mountPath: /opt/docker/etc/app-conf
            - name: logback-conf
              mountPath: /opt/docker/etc/log-conf
